// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import BalanceController from "./balance_controller"
application.register("balance", BalanceController)

import WalletController from "./wallet_controller"
application.register("wallet", WalletController)
